### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kunxl-gg** [kunxl-gg/pixl#1]
Game Engine Milestones.
- [x] Refactor the rendering loop.
- [x] Configure the UI for the engine. 
- [ ] Implement PBR and shadows. 
- [ ] Implement an ECS.
- [x] Setup the sample Sponza scene. 
- [ ] Implement a scripting Engine.
